version: '2'

services:
  master:
    image: redis:3
    command: redis-server --requirepass 12345678 --masterauth 12345678
  slave:
    image: redis:3
    command: redis-server --requirepass 12345678 --masterauth 12345678
    links:
      - master:redis-master
  sentinel:
    build: 
      context: sentinel
      args: 
        - PW=12345678
        - QUORUM=1
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave

